//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinHoaDon
    {
        public int ID_SanPham { get; set; }
        public int ID_HoaDon { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
